dbt_sql:
  target: demo1
  outputs:
    demo1:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      database: SalesDW
      schema: stg
      user: sa
      password: Mario1994c#
      trust_cert: true
    
    demo2:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      database: SalesDW
      schema: dw
      user: sa
      password: Mario1994c#